name: Pull_Request_CI
on:
  pull_request:
    branches:
      - 'main'

env:
  service_name: expense-frontend

jobs:
  CI_Steps:
    uses: akr-org/github-actions/.github/workflows/Pull_Request_Ci.yml@main
    secrets: inherit
    with:
      service_name: expense-frontend