name: Tags_CI
on:
  push:
    tags:
      - "*"

env:
  service_name: expense-frontend

jobs:
  CI_Steps:
    uses: akr-org/github-actions/.github/workflows/Tags_Ci.yml@main
    secrets: inherit
    with:
      service_name: expense-frontend